### PR TITLE
Upgrade to Lucene 7.0.1

### PR DESCRIPTION
**Pull request by nomadicoder**

### CODE REVIEW

**Comment by nomadicoder** [comment]
@dkinzer and @sensei100 Need to know if we have to make other changes I may have missed similar to changes made to Catalog Solr configs.

**Comment by sensei100** [comment]
@nomadicoder Have you looked at this PR where the version was updated in catalog? https://github.com/tulibraries/tul_cob-catalog-solr/pull/10

I would look at whether any of those changes are part of the lucena version change.  I am pretty sure adding the / to search is required.

You will also need to test this locally to make sure you can ingest files with solr.  You could look at the funcake_dags scripts to see how to ingest records if you aren't sure.

**Comment by nomadicoder** [comment]
@dkinzer @sensei100  I added the path to `/search`.  Funcake-solr doesn't have a `document` path.  Is this sufficient?

**Comment by sensei100** [comment]
@nomadicoder Have you tried ingesting records locally?  I don't feel comfortable merging this until we know that we can ingest records without error.

**Comment by dkinzer** [comment]
@nomadicoder once this gets merged: https://github.com/tulibraries/funcake-solr/pull/25

You can rebase this PR and circle will ingest some documents and do a basic search to make sure all is still working.

**Comment by sensei100** [comment]
> @nomadicoder once this gets merged: #25
> 
> You can rebase this PR and circle will ingest some documents and do a basic search to make sure all is still working.

@nomadicoder Since that other PR was merged, it might be nice to rebase this and see if the ingest process works as expected.  It would be nice to be able to finish up this work.

**Comment by nomadicoder** [comment]
@sensei100 I've rebased against main.

**Review by sensei100 — APPROVED** [review]

**Pull request merged**
